// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ContactDocumentDataSlicesSlice = ContactInfoSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type ManifestoDocumentDataSlicesSlice =
  | AwardsSlice
  | BiographyBlockSlice
  | BioSlice
  | HeroSliceSlice;

/**
 * Content for Manifesto documents
 */
interface ManifestoDocumentData {
  /**
   * Slice Zone field in *Manifesto*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: manifesto.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ManifestoDocumentDataSlicesSlice>;
}

/**
 * Manifesto document from Prismic
 *
 * - **API ID**: `manifesto`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ManifestoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ManifestoDocumentData>,
    "manifesto",
    Lang
  >;

type MixedmediaDocumentDataSlicesSlice = MixedMediaInfoSlice;

/**
 * Content for MixedMedia documents
 */
interface MixedmediaDocumentData {
  /**
   * Slice Zone field in *MixedMedia*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: mixedmedia.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MixedmediaDocumentDataSlicesSlice>;
}

/**
 * MixedMedia document from Prismic
 *
 * - **API ID**: `mixedmedia`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MixedmediaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MixedmediaDocumentData>,
    "mixedmedia",
    Lang
  >;

interface NavigationbarDocumentData {}

/**
 * NavigationBar document from Prismic
 *
 * - **API ID**: `navigationbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationbarDocumentData>,
    "navigationbar",
    Lang
  >;

type ProjectpageDocumentDataSlicesSlice =
  | ProjectImageLayout10Slice
  | ProjectImageLayout8Slice
  | ProjectImageLayout7Slice
  | ProjectImageLayout6Slice
  | ProjectImageLayout5Slice
  | EnterButtonSlice
  | ProjectImageLayout4Slice
  | MediaEmbedSlice
  | ProjectPageMediaSlice
  | ProjectImageLayout3Slice
  | SliderImageSlice
  | ProjectTripleImageSlice
  | ProjectVideoSlice
  | ProjectImageLayout2Slice
  | ProjectLayout2Slice
  | ProjectHeaderSlice
  | ProjectImageLayout1Slice
  | ProjectImageSlice
  | ProjectParagraphSlice
  | ProjectHeaderInfoSlice
  | ProjectLayout1Slice;

/**
 * Content for ProjectPage documents
 */
interface ProjectpageDocumentData {
  /**
   * Slice Zone field in *ProjectPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: projectpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectpageDocumentDataSlicesSlice>;
}

/**
 * ProjectPage document from Prismic
 *
 * - **API ID**: `projectpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectpageDocumentData>,
    "projectpage",
    Lang
  >;

type ShowsDocumentDataSlicesSlice = MediaEmbedSlice | ProjectHeaderSlice;

/**
 * Content for Shows documents
 */
interface ShowsDocumentData {
  /**
   * Slice Zone field in *Shows*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: shows.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ShowsDocumentDataSlicesSlice>;
}

/**
 * Shows document from Prismic
 *
 * - **API ID**: `shows`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ShowsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<ShowsDocumentData>, "shows", Lang>;

type SoundDocumentDataSlicesSlice =
  | VimeoSlice
  | SoundLayout5Slice
  | SoundLayout4Slice
  | SoundLayout3Slice
  | SoundLayout2Slice
  | SoundLayout1Slice;

/**
 * Content for Sound documents
 */
interface SoundDocumentData {
  /**
   * Slice Zone field in *Sound*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sound.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SoundDocumentDataSlicesSlice>;
}

/**
 * Sound document from Prismic
 *
 * - **API ID**: `sound`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SoundDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<SoundDocumentData>, "sound", Lang>;

/**
 * Content for Test documents
 */
interface TestDocumentData {
  /**
   * testIMage field in *Test*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: test.testimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  testimage: prismic.ImageField<never>;

  /**
   * testText field in *Test*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: asdifjosdjjo;safidjsafa
   * - **API ID Path**: test.testtext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testtext: prismic.RichTextField;
}

/**
 * Test document from Prismic
 *
 * - **API ID**: `test`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TestDocumentData>, "test", Lang>;

type VideoDocumentDataSlicesSlice = VideoInfoSlice;

/**
 * Content for Video documents
 */
interface VideoDocumentData {
  /**
   * Slice Zone field in *Video*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: video.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<VideoDocumentDataSlicesSlice>;
}

/**
 * Video document from Prismic
 *
 * - **API ID**: `video`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VideoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<VideoDocumentData>, "video", Lang>;

type VideopageDocumentDataSlicesSlice =
  | ProjectParagraphSlice
  | CollaboratorSlice
  | VideoEmbedSlice
  | VideoPageInfoSlice
  | VideoImageSlice
  | VideoPageLayout1Slice;

/**
 * Content for VideoPage documents
 */
interface VideopageDocumentData {
  /**
   * Slice Zone field in *VideoPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: videopage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<VideopageDocumentDataSlicesSlice>;
}

/**
 * VideoPage document from Prismic
 *
 * - **API ID**: `videopage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VideopageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<VideopageDocumentData>,
    "videopage",
    Lang
  >;

export type AllDocumentTypes =
  | ContactDocument
  | ManifestoDocument
  | MixedmediaDocument
  | NavigationbarDocument
  | ProjectpageDocument
  | ShowsDocument
  | SoundDocument
  | TestDocument
  | VideoDocument
  | VideopageDocument;

/**
 * Primary content in *Afdsf → Default → Primary*
 */
export interface AfdsfSliceDefaultPrimary {
  /**
   * iasd field in *Afdsf → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: afdsf.default.primary.iasd
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  iasd: prismic.EmbedField;
}

/**
 * Default variation for Afdsf Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AfdsfSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AfdsfSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Afdsf*
 */
type AfdsfSliceVariation = AfdsfSliceDefault;

/**
 * Afdsf Shared Slice
 *
 * - **API ID**: `afdsf`
 * - **Description**: Afdsf
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AfdsfSlice = prismic.SharedSlice<"afdsf", AfdsfSliceVariation>;

/**
 * Primary content in *Awards → Default → Primary*
 */
export interface AwardsSliceDefaultPrimary {
  /**
   * AwardHonor field in *Awards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: awards.default.primary.awardhonor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  awardhonor: prismic.KeyTextField;
}

/**
 * Default variation for Awards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AwardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AwardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Awards*
 */
type AwardsSliceVariation = AwardsSliceDefault;

/**
 * Awards Shared Slice
 *
 * - **API ID**: `awards`
 * - **Description**: Awards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AwardsSlice = prismic.SharedSlice<"awards", AwardsSliceVariation>;

/**
 * Primary content in *Bio → Default → Primary*
 */
export interface BioSliceDefaultPrimary {
  /**
   * Biography field in *Bio → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio.default.primary.biography
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  biography: prismic.KeyTextField;
}

/**
 * Default variation for Bio Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BioSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BioSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Bio*
 */
type BioSliceVariation = BioSliceDefault;

/**
 * Bio Shared Slice
 *
 * - **API ID**: `bio`
 * - **Description**: Bio
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BioSlice = prismic.SharedSlice<"bio", BioSliceVariation>;

/**
 * Primary content in *BioParagraphs → Default → Primary*
 */
export interface BioParagraphsSliceDefaultPrimary {
  /**
   * BiographySection field in *BioParagraphs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_paragraphs.default.primary.biographysection
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  biographysection: prismic.KeyTextField;
}

/**
 * Default variation for BioParagraphs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BioParagraphsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BioParagraphsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BioParagraphs*
 */
type BioParagraphsSliceVariation = BioParagraphsSliceDefault;

/**
 * BioParagraphs Shared Slice
 *
 * - **API ID**: `bio_paragraphs`
 * - **Description**: BioParagraphs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BioParagraphsSlice = prismic.SharedSlice<
  "bio_paragraphs",
  BioParagraphsSliceVariation
>;

/**
 * Primary content in *BiographyBlock → Default → Primary*
 */
export interface BiographyBlockSliceDefaultPrimary {
  /**
   * BiographyBlock field in *BiographyBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: biography_block.default.primary.biographyblock
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  biographyblock: prismic.KeyTextField;
}

/**
 * Default variation for BiographyBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BiographyBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BiographyBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BiographyBlock*
 */
type BiographyBlockSliceVariation = BiographyBlockSliceDefault;

/**
 * BiographyBlock Shared Slice
 *
 * - **API ID**: `biography_block`
 * - **Description**: BiographyBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BiographyBlockSlice = prismic.SharedSlice<
  "biography_block",
  BiographyBlockSliceVariation
>;

/**
 * Primary content in *Collaborator → Default → Primary*
 */
export interface CollaboratorSliceDefaultPrimary {
  /**
   * name field in *Collaborator → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collaborator.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Default variation for Collaborator Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollaboratorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CollaboratorSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Collaborator*
 */
type CollaboratorSliceVariation = CollaboratorSliceDefault;

/**
 * Collaborator Shared Slice
 *
 * - **API ID**: `collaborator`
 * - **Description**: Collaborator
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollaboratorSlice = prismic.SharedSlice<
  "collaborator",
  CollaboratorSliceVariation
>;

/**
 * Primary content in *ContactInfo → Default → Primary*
 */
export interface ContactInfoSliceDefaultPrimary {
  /**
   * email field in *ContactInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.default.primary.Contact_Email1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Contact_Email1: prismic.KeyTextField;

  /**
   * email2 field in *ContactInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.default.primary.Contact_Email2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Contact_Email2: prismic.KeyTextField;

  /**
   * bookingNA field in *ContactInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.default.primary.Contact_BookingNA
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Contact_BookingNA: prismic.KeyTextField;

  /**
   * bookingEU field in *ContactInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.default.primary.Contact_BookingEU
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Contact_BookingEU: prismic.KeyTextField;
}

/**
 * Default variation for ContactInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactInfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactInfo*
 */
type ContactInfoSliceVariation = ContactInfoSliceDefault;

/**
 * ContactInfo Shared Slice
 *
 * - **API ID**: `contact_info`
 * - **Description**: ContactInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInfoSlice = prismic.SharedSlice<
  "contact_info",
  ContactInfoSliceVariation
>;

/**
 * Primary content in *EnterButton → Default → Primary*
 */
export interface EnterButtonSliceDefaultPrimary {
  /**
   * link field in *EnterButton → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: enter_button.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for EnterButton Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EnterButtonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EnterButtonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EnterButton*
 */
type EnterButtonSliceVariation = EnterButtonSliceDefault;

/**
 * EnterButton Shared Slice
 *
 * - **API ID**: `enter_button`
 * - **Description**: EnterButton
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EnterButtonSlice = prismic.SharedSlice<
  "enter_button",
  EnterButtonSliceVariation
>;

/**
 * Primary content in *HeroSlice → Default → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
  /**
   * Manifesto Hero Image field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.manifesto_hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  manifesto_hero_image: prismic.ImageField<never>;

  /**
   * Manifesto Hero Quote field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.manifesto_hero_quote
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  manifesto_hero_quote: prismic.KeyTextField;
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault;

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSlice = prismic.SharedSlice<
  "hero_slice",
  HeroSliceSliceVariation
>;

/**
 * Primary content in *MediaEmbed → Default → Primary*
 */
export interface MediaEmbedSliceDefaultPrimary {
  /**
   * data field in *MediaEmbed → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: media_embed.default.primary.data
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  data: prismic.EmbedField;
}

/**
 * Default variation for MediaEmbed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaEmbedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MediaEmbedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MediaEmbed*
 */
type MediaEmbedSliceVariation = MediaEmbedSliceDefault;

/**
 * MediaEmbed Shared Slice
 *
 * - **API ID**: `media_embed`
 * - **Description**: MediaEmbed
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaEmbedSlice = prismic.SharedSlice<
  "media_embed",
  MediaEmbedSliceVariation
>;

/**
 * Primary content in *MixedMediaInfo → Default → Primary*
 */
export interface MixedMediaInfoSliceDefaultPrimary {
  /**
   * image field in *MixedMediaInfo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mixed_media_info.default.primary.MixedMediaImage1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  MixedMediaImage1: prismic.ImageField<never>;

  /**
   * url field in *MixedMediaInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mixed_media_info.default.primary.MixedMediaURL
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  MixedMediaURL: prismic.KeyTextField;

  /**
   * Title field in *MixedMediaInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mixed_media_info.default.primary.MixedMediaTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  MixedMediaTitle: prismic.KeyTextField;

  /**
   * Subtitle field in *MixedMediaInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mixed_media_info.default.primary.MixedMediaSubtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  MixedMediaSubtitle: prismic.KeyTextField;
}

/**
 * Default variation for MixedMediaInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MixedMediaInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MixedMediaInfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MixedMediaInfo*
 */
type MixedMediaInfoSliceVariation = MixedMediaInfoSliceDefault;

/**
 * MixedMediaInfo Shared Slice
 *
 * - **API ID**: `mixed_media_info`
 * - **Description**: MixedMediaInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MixedMediaInfoSlice = prismic.SharedSlice<
  "mixed_media_info",
  MixedMediaInfoSliceVariation
>;

/**
 * Primary content in *ProjectHeader → Default → Primary*
 */
export interface ProjectHeaderSliceDefaultPrimary {
  /**
   * header field in *ProjectHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_header.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;
}

/**
 * Default variation for ProjectHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectHeader*
 */
type ProjectHeaderSliceVariation = ProjectHeaderSliceDefault;

/**
 * ProjectHeader Shared Slice
 *
 * - **API ID**: `project_header`
 * - **Description**: ProjectHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectHeaderSlice = prismic.SharedSlice<
  "project_header",
  ProjectHeaderSliceVariation
>;

/**
 * Primary content in *ProjectHeaderInfo → Default → Primary*
 */
export interface ProjectHeaderInfoSliceDefaultPrimary {
  /**
   * Title field in *ProjectHeaderInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_header_info.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *ProjectHeaderInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_header_info.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Default variation for ProjectHeaderInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectHeaderInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectHeaderInfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectHeaderInfo*
 */
type ProjectHeaderInfoSliceVariation = ProjectHeaderInfoSliceDefault;

/**
 * ProjectHeaderInfo Shared Slice
 *
 * - **API ID**: `project_header_info`
 * - **Description**: ProjectHeaderInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectHeaderInfoSlice = prismic.SharedSlice<
  "project_header_info",
  ProjectHeaderInfoSliceVariation
>;

/**
 * Primary content in *ProjectImage → Default → Primary*
 */
export interface ProjectImageSliceDefaultPrimary {
  /**
   * image field in *ProjectImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectImage*
 */
type ProjectImageSliceVariation = ProjectImageSliceDefault;

/**
 * ProjectImage Shared Slice
 *
 * - **API ID**: `project_image`
 * - **Description**: ProjectImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageSlice = prismic.SharedSlice<
  "project_image",
  ProjectImageSliceVariation
>;

/**
 * Primary content in *ProjectImageLayout1 → Default → Primary*
 */
export interface ProjectImageLayout1SliceDefaultPrimary {
  /**
   * context field in *ProjectImageLayout1 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout1.default.primary.context
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  context: prismic.KeyTextField;

  /**
   * video field in *ProjectImageLayout1 → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout1.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for ProjectImageLayout1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout1SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectImageLayout1SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectImageLayout1*
 */
type ProjectImageLayout1SliceVariation = ProjectImageLayout1SliceDefault;

/**
 * ProjectImageLayout1 Shared Slice
 *
 * - **API ID**: `project_image_layout1`
 * - **Description**: ProjectImageLayout1
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout1Slice = prismic.SharedSlice<
  "project_image_layout1",
  ProjectImageLayout1SliceVariation
>;

/**
 * Primary content in *ProjectImageLayout10 → Default → Primary*
 */
export interface ProjectImageLayout10SliceDefaultPrimary {
  /**
   * image1 field in *ProjectImageLayout10 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout10.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *ProjectImageLayout10 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout10.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * image3 field in *ProjectImageLayout10 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout10.default.primary.image3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image3: prismic.ImageField<never>;

  /**
   * image4 field in *ProjectImageLayout10 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout10.default.primary.image4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image4: prismic.ImageField<never>;

  /**
   * image5 field in *ProjectImageLayout10 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout10.default.primary.image5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image5: prismic.ImageField<never>;

  /**
   * image6 field in *ProjectImageLayout10 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout10.default.primary.image6
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image6: prismic.ImageField<never>;

  /**
   * image7 field in *ProjectImageLayout10 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout10.default.primary.image7
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image7: prismic.ImageField<never>;

  /**
   * image8 field in *ProjectImageLayout10 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout10.default.primary.image8
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image8: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectImageLayout10 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout10SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectImageLayout10SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectImageLayout10*
 */
type ProjectImageLayout10SliceVariation = ProjectImageLayout10SliceDefault;

/**
 * ProjectImageLayout10 Shared Slice
 *
 * - **API ID**: `project_image_layout10`
 * - **Description**: ProjectImageLayout10
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout10Slice = prismic.SharedSlice<
  "project_image_layout10",
  ProjectImageLayout10SliceVariation
>;

/**
 * Primary content in *ProjectImageLayout2 → Default → Primary*
 */
export interface ProjectImageLayout2SliceDefaultPrimary {
  /**
   * video field in *ProjectImageLayout2 → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout2.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * context field in *ProjectImageLayout2 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout2.default.primary.context
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  context: prismic.KeyTextField;
}

/**
 * Default variation for ProjectImageLayout2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectImageLayout2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectImageLayout2*
 */
type ProjectImageLayout2SliceVariation = ProjectImageLayout2SliceDefault;

/**
 * ProjectImageLayout2 Shared Slice
 *
 * - **API ID**: `project_image_layout2`
 * - **Description**: ProjectImageLayout2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout2Slice = prismic.SharedSlice<
  "project_image_layout2",
  ProjectImageLayout2SliceVariation
>;

/**
 * Primary content in *ProjectImageLayout3 → Default → Primary*
 */
export interface ProjectImageLayout3SliceDefaultPrimary {
  /**
   * image1 field in *ProjectImageLayout3 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout3.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *ProjectImageLayout3 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout3.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * image3 field in *ProjectImageLayout3 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout3.default.primary.image3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image3: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectImageLayout3 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout3SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectImageLayout3SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectImageLayout3*
 */
type ProjectImageLayout3SliceVariation = ProjectImageLayout3SliceDefault;

/**
 * ProjectImageLayout3 Shared Slice
 *
 * - **API ID**: `project_image_layout3`
 * - **Description**: ProjectImageLayout3
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout3Slice = prismic.SharedSlice<
  "project_image_layout3",
  ProjectImageLayout3SliceVariation
>;

/**
 * Primary content in *ProjectImageLayout4 → Default → Primary*
 */
export interface ProjectImageLayout4SliceDefaultPrimary {
  /**
   * image1 field in *ProjectImageLayout4 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout4.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *ProjectImageLayout4 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout4.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectImageLayout4 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout4SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectImageLayout4SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectImageLayout4*
 */
type ProjectImageLayout4SliceVariation = ProjectImageLayout4SliceDefault;

/**
 * ProjectImageLayout4 Shared Slice
 *
 * - **API ID**: `project_image_layout4`
 * - **Description**: ProjectImageLayout4
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout4Slice = prismic.SharedSlice<
  "project_image_layout4",
  ProjectImageLayout4SliceVariation
>;

/**
 * Primary content in *ProjectImageLayout5 → Default → Primary*
 */
export interface ProjectImageLayout5SliceDefaultPrimary {
  /**
   * image1 field in *ProjectImageLayout5 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout5.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *ProjectImageLayout5 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout5.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectImageLayout5 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout5SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectImageLayout5SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectImageLayout5*
 */
type ProjectImageLayout5SliceVariation = ProjectImageLayout5SliceDefault;

/**
 * ProjectImageLayout5 Shared Slice
 *
 * - **API ID**: `project_image_layout5`
 * - **Description**: ProjectImageLayout5
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout5Slice = prismic.SharedSlice<
  "project_image_layout5",
  ProjectImageLayout5SliceVariation
>;

/**
 * Primary content in *ProjectImageLayout6 → Default → Primary*
 */
export interface ProjectImageLayout6SliceDefaultPrimary {
  /**
   * image1 field in *ProjectImageLayout6 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout6.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *ProjectImageLayout6 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout6.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * image3 field in *ProjectImageLayout6 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout6.default.primary.image3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image3: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectImageLayout6 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout6SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectImageLayout6SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectImageLayout6*
 */
type ProjectImageLayout6SliceVariation = ProjectImageLayout6SliceDefault;

/**
 * ProjectImageLayout6 Shared Slice
 *
 * - **API ID**: `project_image_layout6`
 * - **Description**: ProjectImageLayout6
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout6Slice = prismic.SharedSlice<
  "project_image_layout6",
  ProjectImageLayout6SliceVariation
>;

/**
 * Primary content in *ProjectImageLayout7 → Default → Primary*
 */
export interface ProjectImageLayout7SliceDefaultPrimary {
  /**
   * image1 field in *ProjectImageLayout7 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout7.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *ProjectImageLayout7 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout7.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * image3 field in *ProjectImageLayout7 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout7.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * image4 field in *ProjectImageLayout7 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout7.default.primary.image4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image4: prismic.ImageField<never>;

  /**
   * image5 field in *ProjectImageLayout7 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout7.default.primary.image5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image5: prismic.ImageField<never>;

  /**
   * image6 field in *ProjectImageLayout7 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout7.default.primary.image6
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image6: prismic.ImageField<never>;

  /**
   * image7 field in *ProjectImageLayout7 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout7.default.primary.image7
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image7: prismic.ImageField<never>;

  /**
   * image8 field in *ProjectImageLayout7 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout7.default.primary.image8
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image8: prismic.ImageField<never>;

  /**
   * image9 field in *ProjectImageLayout7 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout7.default.primary.image9
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image9: prismic.ImageField<never>;

  /**
   * media field in *ProjectImageLayout7 → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout7.default.primary.media
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  media: prismic.EmbedField;
}

/**
 * Default variation for ProjectImageLayout7 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout7SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectImageLayout7SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectImageLayout7*
 */
type ProjectImageLayout7SliceVariation = ProjectImageLayout7SliceDefault;

/**
 * ProjectImageLayout7 Shared Slice
 *
 * - **API ID**: `project_image_layout7`
 * - **Description**: ProjectImageLayout7
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout7Slice = prismic.SharedSlice<
  "project_image_layout7",
  ProjectImageLayout7SliceVariation
>;

/**
 * Primary content in *ProjectImageLayout8 → Default → Primary*
 */
export interface ProjectImageLayout8SliceDefaultPrimary {
  /**
   * image1 field in *ProjectImageLayout8 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout8.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *ProjectImageLayout8 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_layout8.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectImageLayout8 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout8SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectImageLayout8SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectImageLayout8*
 */
type ProjectImageLayout8SliceVariation = ProjectImageLayout8SliceDefault;

/**
 * ProjectImageLayout8 Shared Slice
 *
 * - **API ID**: `project_image_layout8`
 * - **Description**: ProjectImageLayout8
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout8Slice = prismic.SharedSlice<
  "project_image_layout8",
  ProjectImageLayout8SliceVariation
>;

/**
 * Default variation for ProjectImageLayout9 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout9SliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ProjectImageLayout9*
 */
type ProjectImageLayout9SliceVariation = ProjectImageLayout9SliceDefault;

/**
 * ProjectImageLayout9 Shared Slice
 *
 * - **API ID**: `project_image_layout9`
 * - **Description**: ProjectImageLayout9
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectImageLayout9Slice = prismic.SharedSlice<
  "project_image_layout9",
  ProjectImageLayout9SliceVariation
>;

/**
 * Primary content in *ProjectLayout1 → Default → Primary*
 */
export interface ProjectLayout1SliceDefaultPrimary {
  /**
   * Header field in *ProjectLayout1 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_layout1.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;
}

/**
 * Default variation for ProjectLayout1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectLayout1SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectLayout1SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectLayout1*
 */
type ProjectLayout1SliceVariation = ProjectLayout1SliceDefault;

/**
 * ProjectLayout1 Shared Slice
 *
 * - **API ID**: `project_layout1`
 * - **Description**: ProjectLayout1
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectLayout1Slice = prismic.SharedSlice<
  "project_layout1",
  ProjectLayout1SliceVariation
>;

/**
 * Primary content in *ProjectLayout2 → Default → Primary*
 */
export interface ProjectLayout2SliceDefaultPrimary {
  /**
   * header field in *ProjectLayout2 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_layout2.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * image field in *ProjectLayout2 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_layout2.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * context field in *ProjectLayout2 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_layout2.default.primary.context
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  context: prismic.KeyTextField;

  /**
   * image2 field in *ProjectLayout2 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_layout2.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectLayout2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectLayout2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectLayout2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectLayout2*
 */
type ProjectLayout2SliceVariation = ProjectLayout2SliceDefault;

/**
 * ProjectLayout2 Shared Slice
 *
 * - **API ID**: `project_layout2`
 * - **Description**: ProjectLayout2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectLayout2Slice = prismic.SharedSlice<
  "project_layout2",
  ProjectLayout2SliceVariation
>;

/**
 * Primary content in *ProjectPageMedia → Default → Primary*
 */
export interface ProjectPageMediaSliceDefaultPrimary {
  /**
   * context field in *ProjectPageMedia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_media.default.primary.context
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  context: prismic.KeyTextField;

  /**
   * image field in *ProjectPageMedia → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_media.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for ProjectPageMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectPageMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectPageMediaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectPageMedia*
 */
type ProjectPageMediaSliceVariation = ProjectPageMediaSliceDefault;

/**
 * ProjectPageMedia Shared Slice
 *
 * - **API ID**: `project_page_media`
 * - **Description**: ProjectPageMedia
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectPageMediaSlice = prismic.SharedSlice<
  "project_page_media",
  ProjectPageMediaSliceVariation
>;

/**
 * Primary content in *ProjectParagraph → Default → Primary*
 */
export interface ProjectParagraphSliceDefaultPrimary {
  /**
   * ProjectParagraph field in *ProjectParagraph → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_paragraph.default.primary.projectparagraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  projectparagraph: prismic.KeyTextField;
}

/**
 * Default variation for ProjectParagraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectParagraphSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectParagraphSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectParagraph*
 */
type ProjectParagraphSliceVariation = ProjectParagraphSliceDefault;

/**
 * ProjectParagraph Shared Slice
 *
 * - **API ID**: `project_paragraph`
 * - **Description**: ProjectParagraph
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectParagraphSlice = prismic.SharedSlice<
  "project_paragraph",
  ProjectParagraphSliceVariation
>;

/**
 * Primary content in *ProjectTripleImage → Default → Primary*
 */
export interface ProjectTripleImageSliceDefaultPrimary {
  /**
   * image1 field in *ProjectTripleImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_triple_image.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *ProjectTripleImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_triple_image.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * image3 field in *ProjectTripleImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_triple_image.default.primary.image3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image3: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectTripleImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectTripleImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectTripleImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectTripleImage*
 */
type ProjectTripleImageSliceVariation = ProjectTripleImageSliceDefault;

/**
 * ProjectTripleImage Shared Slice
 *
 * - **API ID**: `project_triple_image`
 * - **Description**: ProjectTripleImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectTripleImageSlice = prismic.SharedSlice<
  "project_triple_image",
  ProjectTripleImageSliceVariation
>;

/**
 * Primary content in *ProjectVideo → Default → Primary*
 */
export interface ProjectVideoSliceDefaultPrimary {
  /**
   * Header field in *ProjectVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_video.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * video field in *ProjectVideo → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project_video.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for ProjectVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectVideo*
 */
type ProjectVideoSliceVariation = ProjectVideoSliceDefault;

/**
 * ProjectVideo Shared Slice
 *
 * - **API ID**: `project_video`
 * - **Description**: ProjectVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectVideoSlice = prismic.SharedSlice<
  "project_video",
  ProjectVideoSliceVariation
>;

/**
 * Primary content in *SliderImage → Default → Primary*
 */
export interface SliderImageSliceDefaultPrimary {
  /**
   * image field in *SliderImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * caption field in *SliderImage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_image.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

/**
 * Default variation for SliderImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SliderImage*
 */
type SliderImageSliceVariation = SliderImageSliceDefault;

/**
 * SliderImage Shared Slice
 *
 * - **API ID**: `slider_image`
 * - **Description**: SliderImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderImageSlice = prismic.SharedSlice<
  "slider_image",
  SliderImageSliceVariation
>;

/**
 * Primary content in *SoundLayout1 → Default → Primary*
 */
export interface SoundLayout1SliceDefaultPrimary {
  /**
   * image-1 field in *SoundLayout1 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout1.default.primary.s_lo1_image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo1_image_1: prismic.ImageField<never>;

  /**
   * image-2 field in *SoundLayout1 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout1.default.primary.s_lo1_image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo1_image_2: prismic.ImageField<never>;

  /**
   * image-3 field in *SoundLayout1 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout1.default.primary.s_lo1_image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo1_image_3: prismic.ImageField<never>;

  /**
   * Title field in *SoundLayout1 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout1.default.primary.s_lo1_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo1_title: prismic.KeyTextField;

  /**
   * Information field in *SoundLayout1 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout1.default.primary.s_lo1_information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo1_information: prismic.KeyTextField;

  /**
   * Listen field in *SoundLayout1 → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout1.default.primary.s_lo1_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  s_lo1_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for SoundLayout1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SoundLayout1SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SoundLayout1SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SoundLayout1*
 */
type SoundLayout1SliceVariation = SoundLayout1SliceDefault;

/**
 * SoundLayout1 Shared Slice
 *
 * - **API ID**: `sound_layout1`
 * - **Description**: SoundLayout1
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SoundLayout1Slice = prismic.SharedSlice<
  "sound_layout1",
  SoundLayout1SliceVariation
>;

/**
 * Primary content in *SoundLayout2 → Default → Primary*
 */
export interface SoundLayout2SliceDefaultPrimary {
  /**
   * image1 field in *SoundLayout2 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout2.default.primary.s_lo2_image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo2_image_1: prismic.ImageField<never>;

  /**
   * Image2 field in *SoundLayout2 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout2.default.primary.s_lo2_image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo2_image_2: prismic.ImageField<never>;

  /**
   * link field in *SoundLayout2 → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout2.default.primary.s_lo2_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  s_lo2_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * information field in *SoundLayout2 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout2.default.primary.s_lo2_information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo2_information: prismic.KeyTextField;
}

/**
 * Default variation for SoundLayout2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SoundLayout2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SoundLayout2SliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *SoundLayout2 → 3 Images → Primary*
 */
export interface SoundLayout2Slice3ImagesPrimary {
  /**
   * image1 field in *SoundLayout2 → 3 Images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout2.3Images.primary.s_lo2_image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo2_image_1: prismic.ImageField<never>;

  /**
   * Image2 field in *SoundLayout2 → 3 Images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout2.3Images.primary.s_lo2_image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo2_image_2: prismic.ImageField<never>;

  /**
   * Image3 field in *SoundLayout2 → 3 Images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout2.3Images.primary.s_lo2_image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo2_image_3: prismic.ImageField<never>;

  /**
   * link field in *SoundLayout2 → 3 Images → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout2.3Images.primary.s_lo2_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  s_lo2_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * information field in *SoundLayout2 → 3 Images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout2.3Images.primary.s_lo2_information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo2_information: prismic.KeyTextField;
}

/**
 * 3 Images variation for SoundLayout2 Slice
 *
 * - **API ID**: `3Images`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SoundLayout2Slice3Images = prismic.SharedSliceVariation<
  "3Images",
  Simplify<SoundLayout2Slice3ImagesPrimary>,
  never
>;

/**
 * Primary content in *SoundLayout2 → 4 images → Primary*
 */
export interface SoundLayout2Slice4ImagesPrimary {
  /**
   * image1 field in *SoundLayout2 → 4 images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout2.4Images.primary.s_lo2_image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo2_image_1: prismic.ImageField<never>;

  /**
   * Image2 field in *SoundLayout2 → 4 images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout2.4Images.primary.s_lo2_image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo2_image_2: prismic.ImageField<never>;

  /**
   * Image3 field in *SoundLayout2 → 4 images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout2.4Images.primary.s_lo2_image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo2_image_3: prismic.ImageField<never>;

  /**
   * Image4 field in *SoundLayout2 → 4 images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout2.4Images.primary.s_lo2_image_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo2_image_4: prismic.ImageField<never>;

  /**
   * link field in *SoundLayout2 → 4 images → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout2.4Images.primary.s_lo2_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  s_lo2_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * information field in *SoundLayout2 → 4 images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout2.4Images.primary.s_lo2_information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo2_information: prismic.KeyTextField;
}

/**
 * 4 images variation for SoundLayout2 Slice
 *
 * - **API ID**: `4Images`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SoundLayout2Slice4Images = prismic.SharedSliceVariation<
  "4Images",
  Simplify<SoundLayout2Slice4ImagesPrimary>,
  never
>;

/**
 * Slice variation for *SoundLayout2*
 */
type SoundLayout2SliceVariation =
  | SoundLayout2SliceDefault
  | SoundLayout2Slice3Images
  | SoundLayout2Slice4Images;

/**
 * SoundLayout2 Shared Slice
 *
 * - **API ID**: `sound_layout2`
 * - **Description**: SoundLayout2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SoundLayout2Slice = prismic.SharedSlice<
  "sound_layout2",
  SoundLayout2SliceVariation
>;

/**
 * Primary content in *SoundLayout3 → Default → Primary*
 */
export interface SoundLayout3SliceDefaultPrimary {
  /**
   * image field in *SoundLayout3 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.default.primary.s_lo3_image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_image_1: prismic.ImageField<never>;

  /**
   * title field in *SoundLayout3 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.default.primary.s_lo3_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo3_title: prismic.KeyTextField;

  /**
   * text field in *SoundLayout3 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.default.primary.s_lo2_information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo2_information: prismic.KeyTextField;

  /**
   * subtitle field in *SoundLayout3 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.default.primary.s_lo3_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo3_subtitle: prismic.KeyTextField;

  /**
   * subtext field in *SoundLayout3 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.default.primary.s_lo3_subinformation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo3_subinformation: prismic.KeyTextField;

  /**
   * carousel field in *SoundLayout3 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.default.primary.s_lo3_carousel_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_carousel_1: prismic.ImageField<never>;

  /**
   * carousel field in *SoundLayout3 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.default.primary.s_lo3_carousel_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_carousel_2: prismic.ImageField<never>;
}

/**
 * Default variation for SoundLayout3 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SoundLayout3SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SoundLayout3SliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *SoundLayout3 → 3images → Primary*
 */
export interface SoundLayout3Slice3ImagesPrimary {
  /**
   * image field in *SoundLayout3 → 3images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.3Images.primary.s_lo3_image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_image_1: prismic.ImageField<never>;

  /**
   * title field in *SoundLayout3 → 3images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.3Images.primary.s_lo3_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo3_title: prismic.KeyTextField;

  /**
   * text field in *SoundLayout3 → 3images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.3Images.primary.s_lo2_information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo2_information: prismic.KeyTextField;

  /**
   * subtitle field in *SoundLayout3 → 3images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.3Images.primary.s_lo3_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo3_subtitle: prismic.KeyTextField;

  /**
   * subtext field in *SoundLayout3 → 3images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.3Images.primary.s_lo3_subinformation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo3_subinformation: prismic.KeyTextField;

  /**
   * carousel field in *SoundLayout3 → 3images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.3Images.primary.s_lo3_carousel_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_carousel_1: prismic.ImageField<never>;

  /**
   * carousel field in *SoundLayout3 → 3images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.3Images.primary.s_lo3_carousel_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_carousel_2: prismic.ImageField<never>;

  /**
   * carousel field in *SoundLayout3 → 3images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.3Images.primary.s_lo3_carousel_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_carousel_3: prismic.ImageField<never>;
}

/**
 * 3images variation for SoundLayout3 Slice
 *
 * - **API ID**: `3Images`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SoundLayout3Slice3Images = prismic.SharedSliceVariation<
  "3Images",
  Simplify<SoundLayout3Slice3ImagesPrimary>,
  never
>;

/**
 * Primary content in *SoundLayout3 → 4images → Primary*
 */
export interface SoundLayout3Slice4ImagesPrimary {
  /**
   * image field in *SoundLayout3 → 4images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.4Images.primary.s_lo3_image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_image_1: prismic.ImageField<never>;

  /**
   * title field in *SoundLayout3 → 4images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.4Images.primary.s_lo3_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo3_title: prismic.KeyTextField;

  /**
   * text field in *SoundLayout3 → 4images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.4Images.primary.s_lo2_information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo2_information: prismic.KeyTextField;

  /**
   * subtitle field in *SoundLayout3 → 4images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.4Images.primary.s_lo3_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo3_subtitle: prismic.KeyTextField;

  /**
   * subtext field in *SoundLayout3 → 4images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.4Images.primary.s_lo3_subinformation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo3_subinformation: prismic.KeyTextField;

  /**
   * carousel field in *SoundLayout3 → 4images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.4Images.primary.s_lo3_carousel_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_carousel_1: prismic.ImageField<never>;

  /**
   * carousel field in *SoundLayout3 → 4images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.4Images.primary.s_lo3_carousel_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_carousel_2: prismic.ImageField<never>;

  /**
   * carousel field in *SoundLayout3 → 4images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.4Images.primary.s_lo3_carousel_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_carousel_3: prismic.ImageField<never>;

  /**
   * carousel field in *SoundLayout3 → 4images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.4Images.primary.s_lo3_carousel_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_carousel_4: prismic.ImageField<never>;
}

/**
 * 4images variation for SoundLayout3 Slice
 *
 * - **API ID**: `4Images`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SoundLayout3Slice4Images = prismic.SharedSliceVariation<
  "4Images",
  Simplify<SoundLayout3Slice4ImagesPrimary>,
  never
>;

/**
 * Primary content in *SoundLayout3 → 5images → Primary*
 */
export interface SoundLayout3Slice5ImagesPrimary {
  /**
   * image field in *SoundLayout3 → 5images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.5Images.primary.s_lo3_image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_image_1: prismic.ImageField<never>;

  /**
   * title field in *SoundLayout3 → 5images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.5Images.primary.s_lo3_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo3_title: prismic.KeyTextField;

  /**
   * text field in *SoundLayout3 → 5images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.5Images.primary.s_lo2_information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo2_information: prismic.KeyTextField;

  /**
   * subtitle field in *SoundLayout3 → 5images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.5Images.primary.s_lo3_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo3_subtitle: prismic.KeyTextField;

  /**
   * subtext field in *SoundLayout3 → 5images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.5Images.primary.s_lo3_subinformation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo3_subinformation: prismic.KeyTextField;

  /**
   * carousel field in *SoundLayout3 → 5images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.5Images.primary.s_lo3_carousel_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_carousel_1: prismic.ImageField<never>;

  /**
   * carousel field in *SoundLayout3 → 5images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.5Images.primary.s_lo3_carousel_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_carousel_2: prismic.ImageField<never>;

  /**
   * carousel field in *SoundLayout3 → 5images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.5Images.primary.s_lo3_carousel_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_carousel_3: prismic.ImageField<never>;

  /**
   * carousel field in *SoundLayout3 → 5images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.5Images.primary.s_lo3_carousel_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_carousel_4: prismic.ImageField<never>;

  /**
   * carousel field in *SoundLayout3 → 5images → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout3.5Images.primary.s_lo3_carousel_5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo3_carousel_5: prismic.ImageField<never>;
}

/**
 * 5images variation for SoundLayout3 Slice
 *
 * - **API ID**: `5Images`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SoundLayout3Slice5Images = prismic.SharedSliceVariation<
  "5Images",
  Simplify<SoundLayout3Slice5ImagesPrimary>,
  never
>;

/**
 * Slice variation for *SoundLayout3*
 */
type SoundLayout3SliceVariation =
  | SoundLayout3SliceDefault
  | SoundLayout3Slice3Images
  | SoundLayout3Slice4Images
  | SoundLayout3Slice5Images;

/**
 * SoundLayout3 Shared Slice
 *
 * - **API ID**: `sound_layout3`
 * - **Description**: SoundLayout3
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SoundLayout3Slice = prismic.SharedSlice<
  "sound_layout3",
  SoundLayout3SliceVariation
>;

/**
 * Primary content in *SoundLayout4 → Default → Primary*
 */
export interface SoundLayout4SliceDefaultPrimary {
  /**
   * hero field in *SoundLayout4 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout4.default.primary.s_lo4_image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo4_image_1: prismic.ImageField<never>;

  /**
   * text field in *SoundLayout4 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout4.default.primary.s_lo4_information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo4_information: prismic.KeyTextField;

  /**
   * s_lo4_link field in *SoundLayout4 → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout4.default.primary.s_lo4_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  s_lo4_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for SoundLayout4 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SoundLayout4SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SoundLayout4SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SoundLayout4*
 */
type SoundLayout4SliceVariation = SoundLayout4SliceDefault;

/**
 * SoundLayout4 Shared Slice
 *
 * - **API ID**: `sound_layout4`
 * - **Description**: SoundLayout4
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SoundLayout4Slice = prismic.SharedSlice<
  "sound_layout4",
  SoundLayout4SliceVariation
>;

/**
 * Primary content in *SoundLayout5 → Default → Primary*
 */
export interface SoundLayout5SliceDefaultPrimary {
  /**
   * hero field in *SoundLayout5 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout5.default.primary.s_lo5_image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  s_lo5_image_1: prismic.ImageField<never>;

  /**
   * information field in *SoundLayout5 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout5.default.primary.s_lo5_information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  s_lo5_information: prismic.KeyTextField;

  /**
   * link field in *SoundLayout5 → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sound_layout5.default.primary.s_lo5_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  s_lo5_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for SoundLayout5 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SoundLayout5SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SoundLayout5SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SoundLayout5*
 */
type SoundLayout5SliceVariation = SoundLayout5SliceDefault;

/**
 * SoundLayout5 Shared Slice
 *
 * - **API ID**: `sound_layout5`
 * - **Description**: SoundLayout5
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SoundLayout5Slice = prismic.SharedSlice<
  "sound_layout5",
  SoundLayout5SliceVariation
>;

/**
 * Primary content in *VideoEmbed → Default → Primary*
 */
export interface VideoEmbedSliceDefaultPrimary {
  /**
   * media field in *VideoEmbed → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: video_embed.default.primary.media
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  media: prismic.EmbedField;
}

/**
 * Default variation for VideoEmbed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoEmbedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoEmbedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoEmbed*
 */
type VideoEmbedSliceVariation = VideoEmbedSliceDefault;

/**
 * VideoEmbed Shared Slice
 *
 * - **API ID**: `video_embed`
 * - **Description**: VideoEmbed
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoEmbedSlice = prismic.SharedSlice<
  "video_embed",
  VideoEmbedSliceVariation
>;

/**
 * Primary content in *VideoImage → Default → Primary*
 */
export interface VideoImageSliceDefaultPrimary {
  /**
   * image field in *VideoImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for VideoImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoImage*
 */
type VideoImageSliceVariation = VideoImageSliceDefault;

/**
 * VideoImage Shared Slice
 *
 * - **API ID**: `video_image`
 * - **Description**: VideoImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoImageSlice = prismic.SharedSlice<
  "video_image",
  VideoImageSliceVariation
>;

/**
 * Primary content in *VideoInfo → Default → Primary*
 */
export interface VideoInfoSliceDefaultPrimary {
  /**
   * image field in *VideoInfo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_info.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * url field in *VideoInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_info.default.primary.url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url: prismic.KeyTextField;

  /**
   * Title field in *VideoInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_info.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *VideoInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_info.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Default variation for VideoInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoInfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoInfo*
 */
type VideoInfoSliceVariation = VideoInfoSliceDefault;

/**
 * VideoInfo Shared Slice
 *
 * - **API ID**: `video_info`
 * - **Description**: VideoInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoInfoSlice = prismic.SharedSlice<
  "video_info",
  VideoInfoSliceVariation
>;

/**
 * Primary content in *VideoPageInfo → Default → Primary*
 */
export interface VideoPageInfoSliceDefaultPrimary {
  /**
   * title field in *VideoPageInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_page_info.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *VideoPageInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_page_info.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * image field in *VideoPageInfo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_page_info.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * context field in *VideoPageInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_page_info.default.primary.context
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  context: prismic.KeyTextField;
}

/**
 * Default variation for VideoPageInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoPageInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoPageInfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoPageInfo*
 */
type VideoPageInfoSliceVariation = VideoPageInfoSliceDefault;

/**
 * VideoPageInfo Shared Slice
 *
 * - **API ID**: `video_page_info`
 * - **Description**: VideoPageInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoPageInfoSlice = prismic.SharedSlice<
  "video_page_info",
  VideoPageInfoSliceVariation
>;

/**
 * Default variation for VideoPageLayout1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoPageLayout1SliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *VideoPageLayout1*
 */
type VideoPageLayout1SliceVariation = VideoPageLayout1SliceDefault;

/**
 * VideoPageLayout1 Shared Slice
 *
 * - **API ID**: `video_page_layout1`
 * - **Description**: VideoPageLayout1
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoPageLayout1Slice = prismic.SharedSlice<
  "video_page_layout1",
  VideoPageLayout1SliceVariation
>;

/**
 * Primary content in *Vimeo → Default → Primary*
 */
export interface VimeoSliceDefaultPrimary {
  /**
   * url field in *Vimeo → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: vimeo.default.primary.vimeoURL
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  vimeoURL: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * title field in *Vimeo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vimeo.default.primary.Vimeo_Title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Vimeo_Title: prismic.KeyTextField;

  /**
   * information field in *Vimeo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vimeo.default.primary.Vimeo_Information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Vimeo_Information: prismic.KeyTextField;
}

/**
 * Default variation for Vimeo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VimeoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VimeoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Vimeo*
 */
type VimeoSliceVariation = VimeoSliceDefault;

/**
 * Vimeo Shared Slice
 *
 * - **API ID**: `vimeo`
 * - **Description**: Vimeo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VimeoSlice = prismic.SharedSlice<"vimeo", VimeoSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      ManifestoDocument,
      ManifestoDocumentData,
      ManifestoDocumentDataSlicesSlice,
      MixedmediaDocument,
      MixedmediaDocumentData,
      MixedmediaDocumentDataSlicesSlice,
      NavigationbarDocument,
      NavigationbarDocumentData,
      ProjectpageDocument,
      ProjectpageDocumentData,
      ProjectpageDocumentDataSlicesSlice,
      ShowsDocument,
      ShowsDocumentData,
      ShowsDocumentDataSlicesSlice,
      SoundDocument,
      SoundDocumentData,
      SoundDocumentDataSlicesSlice,
      TestDocument,
      TestDocumentData,
      VideoDocument,
      VideoDocumentData,
      VideoDocumentDataSlicesSlice,
      VideopageDocument,
      VideopageDocumentData,
      VideopageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AfdsfSlice,
      AfdsfSliceDefaultPrimary,
      AfdsfSliceVariation,
      AfdsfSliceDefault,
      AwardsSlice,
      AwardsSliceDefaultPrimary,
      AwardsSliceVariation,
      AwardsSliceDefault,
      BioSlice,
      BioSliceDefaultPrimary,
      BioSliceVariation,
      BioSliceDefault,
      BioParagraphsSlice,
      BioParagraphsSliceDefaultPrimary,
      BioParagraphsSliceVariation,
      BioParagraphsSliceDefault,
      BiographyBlockSlice,
      BiographyBlockSliceDefaultPrimary,
      BiographyBlockSliceVariation,
      BiographyBlockSliceDefault,
      CollaboratorSlice,
      CollaboratorSliceDefaultPrimary,
      CollaboratorSliceVariation,
      CollaboratorSliceDefault,
      ContactInfoSlice,
      ContactInfoSliceDefaultPrimary,
      ContactInfoSliceVariation,
      ContactInfoSliceDefault,
      EnterButtonSlice,
      EnterButtonSliceDefaultPrimary,
      EnterButtonSliceVariation,
      EnterButtonSliceDefault,
      HeroSliceSlice,
      HeroSliceSliceDefaultPrimary,
      HeroSliceSliceVariation,
      HeroSliceSliceDefault,
      MediaEmbedSlice,
      MediaEmbedSliceDefaultPrimary,
      MediaEmbedSliceVariation,
      MediaEmbedSliceDefault,
      MixedMediaInfoSlice,
      MixedMediaInfoSliceDefaultPrimary,
      MixedMediaInfoSliceVariation,
      MixedMediaInfoSliceDefault,
      ProjectHeaderSlice,
      ProjectHeaderSliceDefaultPrimary,
      ProjectHeaderSliceVariation,
      ProjectHeaderSliceDefault,
      ProjectHeaderInfoSlice,
      ProjectHeaderInfoSliceDefaultPrimary,
      ProjectHeaderInfoSliceVariation,
      ProjectHeaderInfoSliceDefault,
      ProjectImageSlice,
      ProjectImageSliceDefaultPrimary,
      ProjectImageSliceVariation,
      ProjectImageSliceDefault,
      ProjectImageLayout1Slice,
      ProjectImageLayout1SliceDefaultPrimary,
      ProjectImageLayout1SliceVariation,
      ProjectImageLayout1SliceDefault,
      ProjectImageLayout10Slice,
      ProjectImageLayout10SliceDefaultPrimary,
      ProjectImageLayout10SliceVariation,
      ProjectImageLayout10SliceDefault,
      ProjectImageLayout2Slice,
      ProjectImageLayout2SliceDefaultPrimary,
      ProjectImageLayout2SliceVariation,
      ProjectImageLayout2SliceDefault,
      ProjectImageLayout3Slice,
      ProjectImageLayout3SliceDefaultPrimary,
      ProjectImageLayout3SliceVariation,
      ProjectImageLayout3SliceDefault,
      ProjectImageLayout4Slice,
      ProjectImageLayout4SliceDefaultPrimary,
      ProjectImageLayout4SliceVariation,
      ProjectImageLayout4SliceDefault,
      ProjectImageLayout5Slice,
      ProjectImageLayout5SliceDefaultPrimary,
      ProjectImageLayout5SliceVariation,
      ProjectImageLayout5SliceDefault,
      ProjectImageLayout6Slice,
      ProjectImageLayout6SliceDefaultPrimary,
      ProjectImageLayout6SliceVariation,
      ProjectImageLayout6SliceDefault,
      ProjectImageLayout7Slice,
      ProjectImageLayout7SliceDefaultPrimary,
      ProjectImageLayout7SliceVariation,
      ProjectImageLayout7SliceDefault,
      ProjectImageLayout8Slice,
      ProjectImageLayout8SliceDefaultPrimary,
      ProjectImageLayout8SliceVariation,
      ProjectImageLayout8SliceDefault,
      ProjectImageLayout9Slice,
      ProjectImageLayout9SliceVariation,
      ProjectImageLayout9SliceDefault,
      ProjectLayout1Slice,
      ProjectLayout1SliceDefaultPrimary,
      ProjectLayout1SliceVariation,
      ProjectLayout1SliceDefault,
      ProjectLayout2Slice,
      ProjectLayout2SliceDefaultPrimary,
      ProjectLayout2SliceVariation,
      ProjectLayout2SliceDefault,
      ProjectPageMediaSlice,
      ProjectPageMediaSliceDefaultPrimary,
      ProjectPageMediaSliceVariation,
      ProjectPageMediaSliceDefault,
      ProjectParagraphSlice,
      ProjectParagraphSliceDefaultPrimary,
      ProjectParagraphSliceVariation,
      ProjectParagraphSliceDefault,
      ProjectTripleImageSlice,
      ProjectTripleImageSliceDefaultPrimary,
      ProjectTripleImageSliceVariation,
      ProjectTripleImageSliceDefault,
      ProjectVideoSlice,
      ProjectVideoSliceDefaultPrimary,
      ProjectVideoSliceVariation,
      ProjectVideoSliceDefault,
      SliderImageSlice,
      SliderImageSliceDefaultPrimary,
      SliderImageSliceVariation,
      SliderImageSliceDefault,
      SoundLayout1Slice,
      SoundLayout1SliceDefaultPrimary,
      SoundLayout1SliceVariation,
      SoundLayout1SliceDefault,
      SoundLayout2Slice,
      SoundLayout2SliceDefaultPrimary,
      SoundLayout2Slice3ImagesPrimary,
      SoundLayout2Slice4ImagesPrimary,
      SoundLayout2SliceVariation,
      SoundLayout2SliceDefault,
      SoundLayout2Slice3Images,
      SoundLayout2Slice4Images,
      SoundLayout3Slice,
      SoundLayout3SliceDefaultPrimary,
      SoundLayout3Slice3ImagesPrimary,
      SoundLayout3Slice4ImagesPrimary,
      SoundLayout3Slice5ImagesPrimary,
      SoundLayout3SliceVariation,
      SoundLayout3SliceDefault,
      SoundLayout3Slice3Images,
      SoundLayout3Slice4Images,
      SoundLayout3Slice5Images,
      SoundLayout4Slice,
      SoundLayout4SliceDefaultPrimary,
      SoundLayout4SliceVariation,
      SoundLayout4SliceDefault,
      SoundLayout5Slice,
      SoundLayout5SliceDefaultPrimary,
      SoundLayout5SliceVariation,
      SoundLayout5SliceDefault,
      VideoEmbedSlice,
      VideoEmbedSliceDefaultPrimary,
      VideoEmbedSliceVariation,
      VideoEmbedSliceDefault,
      VideoImageSlice,
      VideoImageSliceDefaultPrimary,
      VideoImageSliceVariation,
      VideoImageSliceDefault,
      VideoInfoSlice,
      VideoInfoSliceDefaultPrimary,
      VideoInfoSliceVariation,
      VideoInfoSliceDefault,
      VideoPageInfoSlice,
      VideoPageInfoSliceDefaultPrimary,
      VideoPageInfoSliceVariation,
      VideoPageInfoSliceDefault,
      VideoPageLayout1Slice,
      VideoPageLayout1SliceVariation,
      VideoPageLayout1SliceDefault,
      VimeoSlice,
      VimeoSliceDefaultPrimary,
      VimeoSliceVariation,
      VimeoSliceDefault,
    };
  }
}
